name: cfRNA_PTB_Model
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - defaults
dependencies:
  - joblib=1.3.2
  - matplotlib=3.8.2
  - minepy=1.2.6
  - numpy=1.26.2
  - pandas=2.1.4
  - python=3.10.13
  - pytorch=2.5.1
  - r-base=4.2.3
  - r-dplyr=1.1.4
  - r-ggfun=0.1.5
  - r-ggplot2=3.5.1
  - r-ggpubr=0.6.0
  - r-ggrepel=0.9.5
  - r-openxlsx=4.2.5.2
  - scipy=1.11.4
  - tqdm=4.66.1
  - xgboost=2.0.3
  - pip:
      - scikit-learn==1.7.0
      - skrebate==0.62
